name: Build

on:
  push:
    branches:
      - "master"
  pull_request:
  workflow_dispatch:

env:
  DOTNET_VERSION: "8.0.x"

jobs:
  windows:
    name: Windows Build
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Capture commit hash
        id: vars
        run: Add-Content $env:GITHUB_OUTPUT "sha_short=$(git rev-parse --short HEAD)"

      - name: Publish self-contained build
        run: >
          dotnet publish 
          -c Release 
          -r win-x64 
          --self-contained true 
          -o output 
          -p:Version=1.0.${{ github.run_number }} 
          -p:InformationalVersion="0.0.${{ github.run_number }}+${{ steps.vars.outputs.sha_short }}"

      - name: Archive build output
        run: |
          $folder = "r6marketplace"
          New-Item $folder -ItemType Directory -Force
          # Recurse ensures subfolders are copied if they exist
          Copy-Item output\* $folder -Recurse
          Compress-Archive -Path $folder -DestinationPath r6marketplace.Windows.zip -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: r6marketplace.Windows
          path: r6marketplace.Windows.zip
          if-no-files-found: error
